### YamlMime:ManagedReference
items:
- uid: Application.Features.ExampleFeature.Services
  commentId: N:Application.Features.ExampleFeature.Services
  id: Application.Features.ExampleFeature.Services
  children:
  - Application.Features.ExampleFeature.Services.ExampleService
  - Application.Features.ExampleFeature.Services.IExampleService
  langs:
  - csharp
  - vb
  name: Application.Features.ExampleFeature.Services
  nameWithType: Application.Features.ExampleFeature.Services
  fullName: Application.Features.ExampleFeature.Services
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.Features.ExampleFeature.Services.IExampleService
  commentId: T:Application.Features.ExampleFeature.Services.IExampleService
  parent: Application.Features.ExampleFeature.Services
  href: Application.Features.ExampleFeature.Services.IExampleService.html
  name: IExampleService
  nameWithType: IExampleService
  fullName: Application.Features.ExampleFeature.Services.IExampleService
- uid: Application.Features.ExampleFeature.Services.ExampleService
  commentId: T:Application.Features.ExampleFeature.Services.ExampleService
  href: Application.Features.ExampleFeature.Services.ExampleService.html
  name: ExampleService
  nameWithType: ExampleService
  fullName: Application.Features.ExampleFeature.Services.ExampleService
- uid: Application.Features.ExampleFeature.Services
  commentId: N:Application.Features.ExampleFeature.Services
  href: Application.html
  name: Application.Features.ExampleFeature.Services
  nameWithType: Application.Features.ExampleFeature.Services
  fullName: Application.Features.ExampleFeature.Services
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Features
    name: Features
    href: Application.Features.html
  - name: .
  - uid: Application.Features.ExampleFeature
    name: ExampleFeature
    href: Application.Features.ExampleFeature.html
  - name: .
  - uid: Application.Features.ExampleFeature.Services
    name: Services
    href: Application.Features.ExampleFeature.Services.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Features
    name: Features
    href: Application.Features.html
  - name: .
  - uid: Application.Features.ExampleFeature
    name: ExampleFeature
    href: Application.Features.ExampleFeature.html
  - name: .
  - uid: Application.Features.ExampleFeature.Services
    name: Services
    href: Application.Features.ExampleFeature.Services.html
