### YamlMime:ManagedReference
items:
- uid: KernelApi.BaseAppSettings
  commentId: T:KernelApi.BaseAppSettings
  id: BaseAppSettings
  parent: KernelApi
  children:
  - KernelApi.BaseAppSettings.ApplicationName
  - KernelApi.BaseAppSettings.ConnectionStrings
  - KernelApi.BaseAppSettings.MaxUsers
  - KernelApi.BaseAppSettings.Password
  - KernelApi.BaseAppSettings.Secret
  langs:
  - csharp
  - vb
  name: BaseAppSettings
  nameWithType: BaseAppSettings
  fullName: KernelApi.BaseAppSettings
  type: Class
  source:
    remote:
      path: src/Kernel/Kernel.Api/BaseAppSettings.cs
      branch: master
      repo: https://github.com/ApricotGambino/Kytc.Boilerplate.Template
    id: BaseAppSettings
    path: ../../src/Kernel/Kernel.Api/BaseAppSettings.cs
    startLine: 5
  assemblies:
  - KernelApi
  namespace: KernelApi
  summary: >-
    This is the base app settings in which all the application must inherit from,

    these are the configurations that the kernel depends on.
  example: []
  syntax:
    content: public class BaseAppSettings
    content.vb: Public Class BaseAppSettings
  inheritance:
  - System.Object
  derivedClasses:
  - Api.AppSettings
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: KernelApi.BaseAppSettings.ConnectionStrings
  commentId: P:KernelApi.BaseAppSettings.ConnectionStrings
  id: ConnectionStrings
  parent: KernelApi.BaseAppSettings
  langs:
  - csharp
  - vb
  name: ConnectionStrings
  nameWithType: BaseAppSettings.ConnectionStrings
  fullName: KernelApi.BaseAppSettings.ConnectionStrings
  type: Property
  source:
    remote:
      path: src/Kernel/Kernel.Api/BaseAppSettings.cs
      branch: master
      repo: https://github.com/ApricotGambino/Kytc.Boilerplate.Template
    id: ConnectionStrings
    path: ../../src/Kernel/Kernel.Api/BaseAppSettings.cs
    startLine: 7
  assemblies:
  - KernelApi
  namespace: KernelApi
  syntax:
    content: public required ConnectionStrings ConnectionStrings { get; set; }
    parameters: []
    return:
      type: KernelApi.ConnectionStrings
    content.vb: Public Property ConnectionStrings As ConnectionStrings
  overload: KernelApi.BaseAppSettings.ConnectionStrings*
- uid: KernelApi.BaseAppSettings.ApplicationName
  commentId: P:KernelApi.BaseAppSettings.ApplicationName
  id: ApplicationName
  parent: KernelApi.BaseAppSettings
  langs:
  - csharp
  - vb
  name: ApplicationName
  nameWithType: BaseAppSettings.ApplicationName
  fullName: KernelApi.BaseAppSettings.ApplicationName
  type: Property
  source:
    remote:
      path: src/Kernel/Kernel.Api/BaseAppSettings.cs
      branch: master
      repo: https://github.com/ApricotGambino/Kytc.Boilerplate.Template
    id: ApplicationName
    path: ../../src/Kernel/Kernel.Api/BaseAppSettings.cs
    startLine: 8
  assemblies:
  - KernelApi
  namespace: KernelApi
  syntax:
    content: public required string ApplicationName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ApplicationName As String
  overload: KernelApi.BaseAppSettings.ApplicationName*
- uid: KernelApi.BaseAppSettings.MaxUsers
  commentId: P:KernelApi.BaseAppSettings.MaxUsers
  id: MaxUsers
  parent: KernelApi.BaseAppSettings
  langs:
  - csharp
  - vb
  name: MaxUsers
  nameWithType: BaseAppSettings.MaxUsers
  fullName: KernelApi.BaseAppSettings.MaxUsers
  type: Property
  source:
    remote:
      path: src/Kernel/Kernel.Api/BaseAppSettings.cs
      branch: master
      repo: https://github.com/ApricotGambino/Kytc.Boilerplate.Template
    id: MaxUsers
    path: ../../src/Kernel/Kernel.Api/BaseAppSettings.cs
    startLine: 9
  assemblies:
  - KernelApi
  namespace: KernelApi
  syntax:
    content: public int MaxUsers { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxUsers As Integer
  overload: KernelApi.BaseAppSettings.MaxUsers*
- uid: KernelApi.BaseAppSettings.Secret
  commentId: P:KernelApi.BaseAppSettings.Secret
  id: Secret
  parent: KernelApi.BaseAppSettings
  langs:
  - csharp
  - vb
  name: Secret
  nameWithType: BaseAppSettings.Secret
  fullName: KernelApi.BaseAppSettings.Secret
  type: Property
  source:
    remote:
      path: src/Kernel/Kernel.Api/BaseAppSettings.cs
      branch: master
      repo: https://github.com/ApricotGambino/Kytc.Boilerplate.Template
    id: Secret
    path: ../../src/Kernel/Kernel.Api/BaseAppSettings.cs
    startLine: 10
  assemblies:
  - KernelApi
  namespace: KernelApi
  syntax:
    content: public required string Secret { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Secret As String
  overload: KernelApi.BaseAppSettings.Secret*
- uid: KernelApi.BaseAppSettings.Password
  commentId: P:KernelApi.BaseAppSettings.Password
  id: Password
  parent: KernelApi.BaseAppSettings
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: BaseAppSettings.Password
  fullName: KernelApi.BaseAppSettings.Password
  type: Property
  source:
    remote:
      path: src/Kernel/Kernel.Api/BaseAppSettings.cs
      branch: master
      repo: https://github.com/ApricotGambino/Kytc.Boilerplate.Template
    id: Password
    path: ../../src/Kernel/Kernel.Api/BaseAppSettings.cs
    startLine: 11
  assemblies:
  - KernelApi
  namespace: KernelApi
  syntax:
    content: public required string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: KernelApi.BaseAppSettings.Password*
references:
- uid: KernelApi
  commentId: N:KernelApi
  href: KernelApi.html
  name: KernelApi
  nameWithType: KernelApi
  fullName: KernelApi
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: KernelApi.BaseAppSettings.ConnectionStrings*
  commentId: Overload:KernelApi.BaseAppSettings.ConnectionStrings
  href: KernelApi.BaseAppSettings.html#KernelApi_BaseAppSettings_ConnectionStrings
  name: ConnectionStrings
  nameWithType: BaseAppSettings.ConnectionStrings
  fullName: KernelApi.BaseAppSettings.ConnectionStrings
- uid: KernelApi.ConnectionStrings
  commentId: T:KernelApi.ConnectionStrings
  parent: KernelApi
  href: KernelApi.ConnectionStrings.html
  name: ConnectionStrings
  nameWithType: ConnectionStrings
  fullName: KernelApi.ConnectionStrings
- uid: KernelApi.BaseAppSettings.ApplicationName*
  commentId: Overload:KernelApi.BaseAppSettings.ApplicationName
  href: KernelApi.BaseAppSettings.html#KernelApi_BaseAppSettings_ApplicationName
  name: ApplicationName
  nameWithType: BaseAppSettings.ApplicationName
  fullName: KernelApi.BaseAppSettings.ApplicationName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: KernelApi.BaseAppSettings.MaxUsers*
  commentId: Overload:KernelApi.BaseAppSettings.MaxUsers
  href: KernelApi.BaseAppSettings.html#KernelApi_BaseAppSettings_MaxUsers
  name: MaxUsers
  nameWithType: BaseAppSettings.MaxUsers
  fullName: KernelApi.BaseAppSettings.MaxUsers
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: KernelApi.BaseAppSettings.Secret*
  commentId: Overload:KernelApi.BaseAppSettings.Secret
  href: KernelApi.BaseAppSettings.html#KernelApi_BaseAppSettings_Secret
  name: Secret
  nameWithType: BaseAppSettings.Secret
  fullName: KernelApi.BaseAppSettings.Secret
- uid: KernelApi.BaseAppSettings.Password*
  commentId: Overload:KernelApi.BaseAppSettings.Password
  href: KernelApi.BaseAppSettings.html#KernelApi_BaseAppSettings_Password
  name: Password
  nameWithType: BaseAppSettings.Password
  fullName: KernelApi.BaseAppSettings.Password
